# Generated by Django 5.1.3 on 2025-04-23 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conceito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Curiosidades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desafios", models.TextField(blank=True, null=True)),
                ("interesses", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("email", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
                ("descricao", models.CharField(blank=True, max_length=200, null=True)),
                ("link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "ano",
                    models.IntegerField(
                        choices=[(1, "1º Ano"), (2, "2º Ano"), (3, "3º Ano")], default=1
                    ),
                ),
                (
                    "semestre",
                    models.IntegerField(
                        choices=[(1, "1º Semestre"), (2, "2º Semestre")], default=1
                    ),
                ),
                ("moodle", models.URLField(blank=True, null=True)),
                ("ulusofona", models.URLField(blank=True, null=True)),
                (
                    "docentes",
                    models.ManyToManyField(
                        related_name="docentes", to="portfolio.docente"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("link_git", models.URLField(blank=True, null=True)),
                ("link_video", models.URLField(blank=True, null=True)),
                ("descricao", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "conceitos",
                    models.ManyToManyField(
                        related_name="conceitos", to="portfolio.conceito"
                    ),
                ),
                (
                    "curiosidades",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curiosidades",
                        to="portfolio.curiosidades",
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplina",
                        to="portfolio.disciplina",
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        related_name="tecnologias", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Imagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="")),
                ("descricao", models.CharField(max_length=200)),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projeto",
                        to="portfolio.projeto",
                    ),
                ),
            ],
        ),
    ]
